export default [
  {
    id: 1,
    name: "Warren Buffett",
    photo: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fthelegacyproject.co.za%2Fwp-content%2Fuploads%2F2015%2F04%2Fwarren-buffett-reuters-1102131.jpg&f=1&nofb=1&ipt=79a0ea27df97e0983d92bc7e50458cada56963c2050c78c5deaa5b81f714957f&ipo=images",
    role: "Chairman & CEO, Berkshire Hathaway",
    netWorth: "$120B+",
    country: "USA",
    industry: "Investment & Conglomerates",
    investmentStrategy: "Value Investing",
    companyFounded: "Berkshire Hathaway (1965 - Acquired)",
    education: "University of Nebraska, Columbia Business School",
    famousQuote:
      "The stock market is designed to transfer money from the Active to the Patient.",
    awards: [
      "Presidential Medal of Freedom (2011)",
      "Named among TIME’s most influential people",
    ],
    keyContributions: [
      "Popularized long-term value investing",
      "Major holdings in Apple, Coca-Cola, and American Express",
      "Philanthropy through The Giving Pledge",
    ],
    bio: "Warren Buffett is one of the most successful investors of all time, known for his disciplined approach to value investing. As the CEO of Berkshire Hathaway, he has turned the company into a massive conglomerate.",
  },
  {
    id: 2,
    name: "Ray Dalio",
    photo: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fstatic1.squarespace.com%2Fstatic%2F5c4d7e227e3c3a6ec70a5ac7%2F5c4f7a82f950b7a7ec9ce527%2F636027fe4cb1004b8ee97d51%2F1687964193844%2FRay%2BDalio.jpg%3Fformat%3D1500w&f=1&nofb=1&ipt=8af116caf8c7f108836eaf391a88e57d9f8965e44b1997357a8e33b1ec5493b3&ipo=images",
    role: "Founder, Bridgewater Associates",
    netWorth: "$16B+",
    country: "USA",
    industry: "Hedge Funds",
    investmentStrategy: "Macro & Risk Parity",
    companyFounded: "Bridgewater Associates (1975)",
    education: "Long Island University, Harvard Business School",
    famousQuote: "Pain + Reflection = Progress.",
    awards: [
      "AI Global Award for Investment Excellence",
      "Named among TIME’s 100 most influential people",
    ],
    keyContributions: [
      "Founded the world's largest hedge fund",
      "Developed 'All Weather' portfolio strategy",
      "Author of 'Principles: Life & Work'",
    ],
    bio: "Ray Dalio is the billionaire investor behind Bridgewater Associates, the world's largest hedge fund. His expertise in economic cycles and risk parity strategies has made him one of the most respected financial minds.",
  },
  {
    id: 3,
    name: "Jamie Dimon",
    photo:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fbitcoinist.com%2Fwp-content%2Fuploads%2F2016%2F02%2FJamie_Dimon2.jpeg&f=1&nofb=1&ipt=84d73b95a1df75e9f27af9a1954ab2dc51d1dd95e4a90b784bf5b66a50059c7d&ipo=images",
    role: "Chairman & CEO, JPMorgan Chase",
    netWorth: "$2B+",
    country: "USA",
    industry: "Banking & Financial Services",
    investmentStrategy: "Banking & Investment Management",
    companyFounded: "N/A (Led JPMorgan Chase)",
    education: "Tufts University, Harvard Business School",
    famousQuote:
      "I don’t worry too much about competitors. I worry about us being better every day.",
    awards: [
      "Fortune’s Businessperson of the Year",
      "Harvard Business School Alumni Achievement Award",
    ],
    keyContributions: [
      "Led JPMorgan Chase to become the largest U.S. bank",
      "Successfully navigated the 2008 financial crisis",
      "Advocated for financial regulation reforms",
    ],
    bio: "Jamie Dimon is the long-time CEO of JPMorgan Chase and is considered one of the most influential figures in global finance. Under his leadership, JPMorgan has become a powerhouse in investment banking and consumer finance.",
  },
  {
    id: 4,
    name: "Ken Griffin",
    photo:
      "https://media.zenfs.com/en/business_insider_articles_888/0bfc35206948c591c40387b60ce18ee6",
    role: "Founder & CEO, Citadel",
    netWorth: "$35B+",
    country: "USA",
    industry: "Hedge Funds & Market Making",
    investmentStrategy: "Quantitative & High-Frequency Trading",
    companyFounded: "Citadel (1990), Citadel Securities (2001)",
    education: "Harvard University",
    famousQuote:
      "We are in the business of taking risks, but we only take risks we understand.",
    awards: ["Institutional Investor Hedge Fund Manager of the Year"],
    keyContributions: [
      "Runs one of the most profitable hedge funds",
      "Major player in market-making through Citadel Securities",
      "Influences regulatory discussions on financial markets",
    ],
    bio: "Ken Griffin founded Citadel, one of the most successful hedge funds in the world. His firm is a leader in quantitative trading and market-making, playing a crucial role in global financial markets.",
  },
  {
    id: 5,
    name: "Larry Fink",
    photo: "http://media.vanityfair.com/photos/54cc03023c894ccb27c877b3/master/h_606,c_limit/image.jpg",
    role: "Chairman & CEO, BlackRock",
    netWorth: "$1B+",
    country: "USA",
    industry: "Asset Management",
    investmentStrategy: "ESG Investing & Passive Investing",
    companyFounded: "BlackRock (1988)",
    education: "University of California, Los Angeles (UCLA)",
    famousQuote: "Climate risk is investment risk.",
    awards: ["CEO of the Year by Financial Times"],
    keyContributions: [
      "Leads the world's largest asset manager ($10T AUM)",
      "Strong advocate for ESG (Environmental, Social, and Governance) investing",
      "Developed iShares ETF market dominance",
    ],
    bio: "Larry Fink is the CEO of BlackRock, the world's largest asset manager. He has been a vocal advocate for responsible investing and has driven the growth of ETFs and index funds.",
  },
  {
    id: 6,
    name: "Carl Icahn",
    photo:
      "https://2.bp.blogspot.com/-icTKNYQkc7E/WFsyX-SYRsI/AAAAAAAA7N0/L0K-TiwH5kkVgwV7MH0Clpi3Rp_6uLHrACLcB/s1600/carl-icahn.jpg",
    role: "Founder, Icahn Enterprises",
    netWorth: "$20B+",
    country: "USA",
    industry: "Activist Investing",
    investmentStrategy: "Corporate Takeovers & Restructuring",
    companyFounded: "Icahn Enterprises (1987)",
    education: "Princeton University",
    famousQuote:
      "In life and business, there are two cardinal sins: the first is to act without thought, the second is to not act at all.",
    awards: ["Forbes' Most Influential Investors"],
    keyContributions: [
      "Expert in corporate takeovers and restructuring",
      "Played key roles in major corporate battles (e.g., Apple, Yahoo)",
      "Influenced shareholder activism worldwide",
    ],
    bio: "Carl Icahn is a legendary activist investor known for shaking up companies and forcing management to unlock shareholder value through strategic corporate changes.",
  },
  {
    id: 7,
    name: "Jim Simons",
    photo:
      "https://simonsfoundation.imgix.net/wp-content/uploads/2024/05/09150139/JimSimons_05_Bea-de-Ghea_Rectangle-scaled.jpg?auto=format&q=90",
    role: "Founder, Renaissance Technologies",
    netWorth: "$30B+",
    country: "USA",
    industry: "Hedge Funds & Quantitative Trading",
    investmentStrategy: "Algorithmic & AI-Based Trading",
    companyFounded: "Renaissance Technologies (1982)",
    education: "MIT, University of California, Berkeley",
    famousQuote: "Luck plays a meaningful role in everyone’s life.",
    awards: ["Mathematical Sciences Lifetime Achievement Award"],
    keyContributions: [
      "Developed the Medallion Fund, with 66% average annual returns",
      "Pioneered AI and machine learning in trading",
      "Mathematician turned legendary hedge fund manager",
    ],
    bio: "Jim Simons is a pioneer in quantitative investing, using advanced mathematics and machine learning to create some of the highest-performing hedge funds in history.",
  },
  {
    id: 8,
    name: "Mark Sorrell",
    photo: "https://www.faytechcc.edu/wp-content/uploads/2022/09/Mark-Sorrells-President-Elect-940x1525.jpg",
    role: "Global Head of Industrials, Goldman Sachs",
    netWorth: "Not Publicly Disclosed",
    country: "UK",
    industry: "Investment Banking",
    investmentStrategy: "Mergers & Acquisitions",
    companyFounded: "N/A",
    education: "Oxford University",
    famousQuote: "Strategic partnerships drive industrial growth.",
    awards: ["Top Dealmakers in Europe 2024"],
    keyContributions: [
      "Advised on £70.6bn worth of transactions in 2024",
      "Led major industrial mergers and acquisitions",
      "Instrumental in high-profile European deals",
    ],
    bio: "Mark Sorrell is a prominent figure in investment banking, leading significant industrial sector deals across Europe. His expertise has been pivotal in shaping major mergers and acquisitions.",
  },
  {
    id: 9,
    name: "Neel Sachdev",
    photo: "https://images.law.com/contrib/content/uploads/sites/378/2021/05/neel-sachdev-kirkland-Article-202105170706.jpg",
    role: "Partner, Paul Weiss",
    netWorth: "Not Publicly Disclosed",
    country: "UK",
    industry: "Legal Advisory in Finance",
    investmentStrategy: "Private Equity Transactions",
    companyFounded: "N/A",
    education: "Cambridge University",
    famousQuote: "Private equity is the catalyst for innovation.",
    awards: ["Top Finance Lawyers in EMEA 2024"],
    keyContributions: [
      "Advised on £39.5bn worth of finance deals in 2024",
      "Key advisor in major private equity transactions",
      "Expanded Paul Weiss's presence in London",
    ],
    bio: "Neel Sachdev is a leading finance lawyer specializing in private equity. His strategic insights have facilitated significant transactions, bolstering the firm's reputation in the financial sector.",
  },
  {
    id: 10,
    name: "Tony Robbins",
    photo: "https://i.pinimg.com/736x/90/de/89/90de890f4343fce2f10a130f8d215d23.jpg",
    role: "Author and Financial Educator",
    netWorth: "$600M+",
    country: "USA",
    industry: "Financial Education",
    investmentStrategy: "Personal Finance and Wealth Management",
    companyFounded: "Robbins Research International",
    education: "High School Diploma",
    famousQuote:
      "The secret to wealth is simple: find a way to do more for others than anyone else does.",
    awards: ["Top Financial Influencers to Follow"],
    keyContributions: [
      "Authored 'Money: Master the Game'",
      "Provides financial education through seminars and workshops",
      "Empowers individuals to achieve financial freedom",
    ],
    bio: "Tony Robbins is a renowned author and speaker, focusing on personal finance and wealth management. His teachings have inspired millions to take control of their financial destinies.",
  },
];
